### ISSUE TITLE
NSFW: Type only domain here

### ISSUE THREAD

**Issue by Yoon455** [Yoon455/pornhosts#1]
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

```python
example.net
www.example.net
```

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
